import React from 'react';

function About() {
    return(
        <div className='section about' id='about'>
            <div className='container'>
                <div className='row'>
                    <div className='col-12'>
                        <div className='content'>
                            <h1>Wesley (Wes) Lewis</h1>
                            <p className='sub'>Saxophonist, Composer, and Arranger</p>
                            <br />
                            <p>Wesley (Wes) Lewis is a saxophonist, composer, and arranger based in New Haven, CT. He has studied under multiple Grammy award winning musicians including&nbsp;<a href="https://en.wikipedia.org/wiki/Wayne_Escoffery" target="_blank" rel="noreferrer">Wayne Escoffery</a>,&nbsp;<a href="https://en.wikipedia.org/wiki/Abraham_Burton" target="_blank" rel="noreferrer">Abraham Burton</a>, and&nbsp;<a href="https://arts-sciences.buffalo.edu/music/faculty/faculty-directory.host.html/content/shared/arts-sciences/music/new-faculty-profiles/caldwell-george.html" target="_blank" rel="noreferrer">George Caldwell</a>. Arriving in New Haven CT in 2019, Wes quickly made a name for himself via performances at the Yale School of Music, and as a principal member of the Yale Jazz Ensemble and Yale Jazz Combos. In 2023, Wes performed Charles Mingus&#39; behemoth composition,&nbsp;<a href="https://jazztimes.com/features/profiles/charles-mingus-epitaph-lost-and-found/" target="_blank" rel="noreferrer">Epitaph</a>, alongside the Grammy winning&nbsp;<a href="https://en.wikipedia.org/wiki/Mingus_Big_Band" target="_blank" rel="noreferrer">Mingus Big Band</a>, under the direction of&nbsp;<a href="https://en.wikipedia.org/wiki/Frank_Lacy" target="_blank" rel="noreferrer">Kuumba Frank Lacy</a>&nbsp;and Wayne Escoffery. Other recent cornerstones of Wes&#39; musical achievement include performances at&nbsp;<a href="https://2023.jazz.org/dizzys-clu" target="_blank" rel="noreferrer">Dizzy&#39;s</a>&nbsp;(Jazz at Lincoln Center) alongside tenor saxophone giant&nbsp;<a href="https://en.wikipedia.org/wiki/George_Coleman" target="_blank" rel="noreferrer">George Coleman</a>,&nbsp;as well as a series of sound baths commissioned by&nbsp;<a href="https://www.nxthvn.com/" target="_blank" rel="noreferrer">NXTHVN</a>,&nbsp;the gallery founded by artist and MacArthur &quot;Genius&quot; Fellowship recipient&nbsp;<a href="https://en.wikipedia.org/wiki/Titus_Kaphar" target="_blank" rel="noreferrer">Titus Kaphar</a>. In September of 2023, Wes was awarded the Mellon Foundation&#39;s &quot;Artist Corps&quot; grant, providing $20,000 toward the creation of the New Haven Composers Spotlight. The Spotlight aims to reduce the segmentation between musical communities of New Haven, CT, by commissioning a large ensemble to perform the works of local BIPOC musicians. Wes is the primary curator and director for this project.</p>
                            <p>In 13 years of performing professionally, Wes has played at an array of public and private venues in the Connecticut, Massachusetts, Rhode Island, NYC, and Western NY jazz scenes, including&nbsp;<a href="https://woolsey.yale.edu/" target="_blank" rel="noreferrer">Woolsey Hall</a>,&nbsp;Jazz at Lincoln Center, RD86 Space,&nbsp;NXTHVN, Cafe 9,&nbsp;The State House, Oasis Pub,&nbsp;Three Sheets, Encore! By Goodfellas, News Cafe, Jack&#39;s Bar and Steakhouse,&nbsp;<a href="https://redscrollrecords.com/" target="_blank" rel="noreferrer">Redscroll Records</a>,&nbsp;<a href="https://www.lewistonjazz.com/" target="_blank" rel="noreferrer">the&nbsp;Lewiston Jazz Festival</a>,&nbsp;and others.&nbsp;</p>
                            <p>Alongside the Yale ensembles, Wes frequently performs with&nbsp;<a href="https://wes-lewis.bandcamp.com/album/trance-macabre-live-at-the-state-house" target="_blank" rel="noreferrer">Trance Macabre</a>, a collective dedicated to merging jazz and dance influences with collective composition. Founded by bassist and sculptor Nicholas Serrambana, Trance Macabre features a cast improvisers including Vigilence Brandon, Cameron Campbell, Ryan Sands, Michael Larocca, Autumn Asbridge, and others. He also leads the Wes Lewis Quartet, which includes Derek Lewis on piano, Conway Campbell Jr. and Zwelakhe-Duma Bell Le Pere&nbsp;on bass, and Ryan Sands on drums. Trance Macabre is set to record its first studio LP in October of 2023, and is planning to release this LP on the&nbsp;<a href="https://redscrollrecords.com/" target="_blank" rel="noreferrer">Redscroll Records</a>&nbsp;label.</p>
                            <p>Wes initially began studying saxophone in the fourth grade and has performed professionally since the age of 14. While still in Buffalo, he performed with the award-winning SHCHS Jazz Ensemble and co-founded the Luke Ciminelli Quintet and Small Combo in 2011. He also played in the University at Buffalo Big Bands from 2014-2015, before touring Europe within a concert band for&nbsp;<a href="https://www.americanmusicabroad.com/" target="_blank" rel="noreferrer">American Music Abroad</a>&nbsp;in late 2015. After absorbing a more expansive scope of jazz music as an undergraduate at the University of Rochester, Wes moved to New Haven to pursue further musical opportunities alongside a PhD in Computational Biology and Bioinformatics&nbsp;<a href="https://cbb.yale.edu/" target="_blank" rel="noreferrer">(Yale CBB)</a>&nbsp;at Yale University. In the future, Wes aims to perform widely as a jazz and contemporary saxophonist while growing as a band leader, composer and arranger, and is interested in using the techniques and perspectives that his skills in machine learning and algorithm development lend to his musical and compositional acumen.&nbsp;</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

export default About;